name: clj-kondo linter

on: [push, pull_request]

jobs:
  clj-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src test
        github_token: ${{ secrets.GITHUB_TOKEN }}
