name: Clojure CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: SPECIALPASSWORD
        ports:
          - 5432:5432

    steps:
      - name: psycopg2 prerequisites
        run: sudo apt-get update

      - name: psycopg2 prerequisites
        run: sudo apt-get install -y libpq-dev

      - uses: actions/checkout@v2
      - name: Run tests
        uses: vouch-opensource/tools.deps-build@1.0.1
        env:
          PGPASSWORD: SPECIALPASSWORD
